'''
# Make text colorfull on terminals
'''

# Text Colors
BLACK = '\033[30m'
RED = '\033[31m'
GREEN = '\033[32m'
YELLOW = '\033[33m'
BLUE = '\033[34m'
MAGENTA = '\033[35m'
CYAN = '\033[36m'
WHITE = '\033[37m'

# Bright Text Colors
BRIGHT_BLACK = '\033[90m'
BRIGHT_RED = '\033[91m'
BRIGHT_GREEN = '\033[92m'
BRIGHT_YELLOW = '\033[93m'
BRIGHT_BLUE = '\033[94m'
BRIGHT_MAGENTA = '\033[95m'
BRIGHT_CYAN = '\033[96m'
BRIGHT_WHITE = '\033[97m'

# Background Colors
BG_BLACK = '\033[40m'
BG_RED = '\033[41m'
BG_GREEN = '\033[42m'
BG_YELLOW = '\033[43m'
BG_BLUE = '\033[44m'
BG_MAGENTA = '\033[45m'
BG_CYAN = '\033[46m'
BG_WHITE = '\033[47m'

# Bright Background Colors
BG_BRIGHT_BLACK = '\033[100m'
BG_BRIGHT_RED = '\033[101m'
BG_BRIGHT_GREEN = '\033[102m'
BG_BRIGHT_YELLOW = '\033[103m'
BG_BRIGHT_BLUE = '\033[104m'
BG_BRIGHT_MAGENTA = '\033[105m'
BG_BRIGHT_CYAN = '\033[106m'
BG_BRIGHT_WHITE = '\033[107m'

# Light (Bright) Text Colors
LIGHT_BLACK = '\033[90m'
LIGHT_RED = '\033[91m'
LIGHT_GREEN = '\033[92m'
LIGHT_YELLOW = '\033[93m'
LIGHT_BLUE = '\033[94m'
LIGHT_MAGENTA = '\033[95m'
LIGHT_CYAN = '\033[96m'
LIGHT_WHITE = '\033[97m'

# Light (Bright) Background Colors
BG_LIGHT_BLACK = '\033[100m'
BG_LIGHT_RED = '\033[101m'
BG_LIGHT_GREEN = '\033[102m'
BG_LIGHT_YELLOW = '\033[103m'
BG_LIGHT_BLUE = '\033[104m'
BG_LIGHT_MAGENTA = '\033[105m'
BG_LIGHT_CYAN = '\033[106m'
BG_LIGHT_WHITE = '\033[107m'


# Text Decorations
RESET = '\033[0m'
BOLD = '\033[1m'
DIM = '\033[2m'
ITALIC = '\033[3m'
UNDERLINE = '\033[4m'
BLINK = '\033[5m'
REVERSE = '\033[7m'
HIDDEN = '\033[8m'
STRIKETHROUGH = '\033[9m'

# Example usage
"""
print(f"{RED}This is red text{RESET}")
print(f"{BG_GREEN}This has a green background{RESET}")
print(f"{BOLD}This is bold text{RESET}")
print(f"{UNDERLINE}This is underlined text{RESET}")
print(f"{RED}This is red text{RESET}")
print(f"{BOLD}{UNDERLINE}{GREEN}Bold, underlined green text{RESET}")
"""

# ALL
ALL_COLORS = f'''
{BLACK}BLACK{RESET}
{RED}RED{RESET}
{GREEN}GREEN{RESET}
{YELLOW}YELLOW{RESET}
{BLUE}BLUE{RESET}
{MAGENTA}MAGENTA{RESET}
{CYAN}CYAN{RESET}
{WHITE}WHITE{RESET}
{BRIGHT_BLACK}BRIGHT_BLACK{RESET}
{BRIGHT_RED}BRIGHT_RED{RESET}
{BRIGHT_GREEN}BRIGHT_GREEN{RESET}
{BRIGHT_YELLOW}BRIGHT_YELLOW{RESET}
{BRIGHT_BLUE}BRIGHT_BLUE{RESET}
{BRIGHT_MAGENTA}BRIGHT_MAGENTA{RESET}
{BRIGHT_CYAN}BRIGHT_CYAN{RESET}
{BRIGHT_WHITE}BRIGHT_WHITE{RESET}
{BG_BLACK}BG_BLACK{RESET}
{BG_RED}BG_RED{RESET}
{BG_GREEN}BG_GREEN{RESET}
{BG_YELLOW}BG_YELLOW{RESET}
{BG_BLUE}BG_BLUE{RESET}
{BG_MAGENTA}BG_MAGENTA{RESET}
{BG_CYAN}BG_CYAN{RESET}
{BG_WHITE}BG_WHITE{RESET}
{BG_BRIGHT_BLACK}BG_BRIGHT_BLACK{RESET}
{BG_BRIGHT_RED}BG_BRIGHT_RED{RESET}
{BG_BRIGHT_GREEN}BG_BRIGHT_GREEN{RESET}
{BG_BRIGHT_YELLOW}BG_BRIGHT_YELLOW{RESET}
{BG_BRIGHT_BLUE}BG_BRIGHT_BLUE{RESET}
{BG_BRIGHT_MAGENTA}BG_BRIGHT_MAGENTA{RESET}
{BG_BRIGHT_CYAN}BG_BRIGHT_CYAN{RESET}
{BG_BRIGHT_WHITE}BG_BRIGHT_WHITE{RESET}
{LIGHT_BLACK}LIGHT_BLACK{RESET}
{LIGHT_RED}LIGHT_RED{RESET}
{LIGHT_GREEN}LIGHT_GREEN{RESET}
{LIGHT_YELLOW}LIGHT_YELLOW{RESET}
{LIGHT_BLUE}LIGHT_BLUE{RESET}
{LIGHT_MAGENTA}LIGHT_MAGENTA{RESET}
{LIGHT_CYAN}LIGHT_CYAN{RESET}
{LIGHT_WHITE}LIGHT_WHITE{RESET}
{BG_LIGHT_BLACK}BG_LIGHT_BLACK{RESET}
{BG_LIGHT_RED}BG_LIGHT_RED{RESET}
{BG_LIGHT_GREEN}BG_LIGHT_GREEN{RESET}
{BG_LIGHT_YELLOW}BG_LIGHT_YELLOW{RESET}
{BG_LIGHT_BLUE}BG_LIGHT_BLUE{RESET}
{BG_LIGHT_MAGENTA}BG_LIGHT_MAGENTA{RESET}
{BG_LIGHT_CYAN}BG_LIGHT_CYAN{RESET}
{BG_LIGHT_WHITE}BG_LIGHT_WHITE{RESET}
'''